#image: quay.io/ssmiller25/gitpod-k8s:latest
image: quay.io/ssmiller25/gitpod-k8s:pr-13
tasks:
  - name: Login to Cloud Resources
    command: |
      bash $HOME/scripts/00-cloudinit.sh
  - name: Install Hugo
    init: |
      brew install hugo
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools